axonivy/engine-cockpit

engine-cockpit/src/ch/ivyteam/enginecockpit/system/LoginBean.java

seems broken because of: https://github.com/axonivy/engine-cockpit/pull/1340

XIVY-17009 Fix auto-login in designer

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/services/WebTestWebServiceProcesses.java
engine-cockpit-test-data/dataclasses/engine/cockpit/test/data/TestWebServiceProcessCockpitData.d.json
engine-cockpit-test-data/processes/TestWebServiceProcessCockpit.p.json
engine-cockpit/webContent/view/webserviceprocesses.xhtml

for https://github.com/axonivy/engine-cockpit/pull/1449

XIVY-17174 Add web service processes test

---

.ivy/raise-deps.sh
maven-config/pom.xml

XIVY-17200 fix: manage ivy-api-bom version with raise-deps

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/services/WebTestSearchEngine.java

https://github.com/axonivy/engine-cockpit/pull/1482

Try stabilize `WebTestSearchEngine#queryTool` test > R12

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/services/WebTestSearchEngine.java

https://github.com/axonivy/engine-cockpit/pull/1482

Try stabilize `WebTestSearchEngine#queryTool` test > R13.1

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/docu/WebDocuScreenshot.java
engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/monitor/WebTestJobs.java
engine-cockpit/webContent/view/monitorJobs.xhtml

https://github.com/axonivy/engine-cockpit/pull/1491

Try stabilize jobs tests > R13.1

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/system/WebTestSSL.java
engine-cockpit/src/ch/ivyteam/enginecockpit/system/ssl/KeyStoreBean.java
engine-cockpit/src/ch/ivyteam/enginecockpit/system/ssl/KeyStoreUtils.java
engine-cockpit/src/ch/ivyteam/enginecockpit/system/ssl/SslTableStore.java
engine-cockpit/src/ch/ivyteam/enginecockpit/system/ssl/TrustStoreBean.java
engine-cockpit/webContent/includes/components/configuration/ssl-keystore.xhtml
engine-cockpit/webContent/includes/components/configuration/ssl-truststore.xhtml
engine-cockpit/webContent/resources/composite/SslTable.xhtml

https://github.com/axonivy/engine-cockpit/pull/1492

XIVY-16125 Add Error message for SSL Cert import

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/monitor/WebTestSessions.java

Try stabilize killSession test, by wait until new tab/page is loaded until open there a new url

Try stabilize WebTestSessions#killSession test

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/monitor/WebTestSessions.java

https://github.com/axonivy/engine-cockpit/pull/1520

Try stabilize WebTestSessions#killSession test > R13.1

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/security/WebTestSecuritySystemDetail.java

https://github.com/axonivy/engine-cockpit/pull/1519

Try stabilize security system language change tests > R13.1

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/monitor/WebTestSessions.java

https://github.com/axonivy/engine-cockpit/pull/1520

Try stabilize WebTestSessions#killSession test > R10

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/system/WebTestSSL.java
engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/util/Navigation.java
engine-cockpit/webContent/includes/components/configuration/ssl-keystore.xhtml
engine-cockpit/webContent/includes/components/configuration/ssl-truststore.xhtml
engine-cockpit/webContent/resources/js/sidebar-fix.js

- Combine tests, remove nesting
- Don't see any benefit from split them to this smaller parts
- Remove update `@all`, as it seems to break the navigation sidebar
- Modernize sidebar-fix.js

Fix WebTestSSL tests

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/system/WebTestSSL.java
engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/util/Navigation.java
engine-cockpit/webContent/includes/components/configuration/ssl-keystore.xhtml
engine-cockpit/webContent/includes/components/configuration/ssl-truststore.xhtml
engine-cockpit/webContent/resources/js/sidebar-fix.js

- Combine tests, remove nesting
- Don't see any benefit from split them to this smaller parts
- Remove update `@all`, as it seems to break the navigation sidebar
- Modernize sidebar-fix.js
https://github.com/axonivy/engine-cockpit/pull/1528

Simplify WebTestSSL tests > R13.1

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/services/WebTestTlsTester.java
engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/system/WebTestConfigFileEditor.java
engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/system/WebTestSSL.java
engine-cockpit/src/ch/ivyteam/enginecockpit/system/ssl/KeyStoreBean.java
engine-cockpit/src/ch/ivyteam/enginecockpit/system/ssl/TrustStoreBean.java
engine-cockpit/webContent/resources/composite/SslTable.xhtml

https://github.com/axonivy/engine-cockpit/pull/1517

XIVY-16125 Add Confirm Dialog for deleting Certs > 12

---

build/build.groovy

https://github.com/axonivy/engine-cockpit/pull/1532

Ignore maven warning about failing UserSynchronizer job > R13.1

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/security/WebTestSecuritySystemDetail.java

https://github.com/axonivy/engine-cockpit/pull/1519

Try stabilize security system language change tests > r10

---

engine-cockpit/src/ch/ivyteam/enginecockpit/monitor/OsBean.java

Display committed memory sizes as jvm memory usage
Will merge to 12 and 10

XIVY-17380 Fix jvm memory usage chart

---

engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/util/EngineCockpitUtil.java
engine-cockpit-selenium-test/test/ch/ivyteam/enginecockpit/util/Navigation.java
engine-cockpit/webContent/resources/js/sidebar-fix.js

https://github.com/axonivy/engine-cockpit/pull/1565

Stabilize navigation for tests (try fix WebTestSecurityIdentityProvider) > R13.1

---

engine-cockpit/cms/cms_de.yaml

Currently translated at 99.7% (1271 of 1274 strings)
Translation: axonivy/engine-cockpit
Translate-URL: https://hosted.weblate.org/projects/axonivy/engine-cockpit/de/

Translated using Weblate (German)

---

engine-cockpit-test-data/src/ch/ivyteam/enginecockpit/testdata/security/identity/DummyIdentityProvider.java
engine-cockpit/src/ch/ivyteam/enginecockpit/security/directory/DirectoryBrowserBean.java
engine-cockpit/webContent/resources/composite/DirectoryBrowser.xhtml

https://github.com/axonivy/core/pull/10312

XIVY-17531 Enable paging on Directory browser
